// @responsibility Backward-compatible re-export for shadow type consumers.
export type {
  EngineMode,
  ExecutionImpact,
  ShadowLifecycleState,
  ShadowStateTransition,
  DataHealth,
  ProviderHealth,
  ConfidenceLevel,
  SourceConfidence,
  ShadowCase,
  OutcomeLabel,
  IntegrityIssue,
  IntegritySeverity,
  ReturnFlowCheck,
  PromotionReport,
  PromotionStatus,
  RegimeConfidence,
  RegimePhase,
} from './types/index.js';
