// @responsibility Shadow Learning Genius Patch v1 상수 — magic number SSOT
export const SHADOW_PROMOTION_MIN_SAMPLE_SIZE = 100;
export const SHADOW_PROMOTION_MIN_CLOSED_SAMPLE_RATE = 0.85;
export const SHADOW_PROMOTION_MIN_LABEL_COMPLETION_RATE = 0.95;
export const SHADOW_PROMOTION_MAX_DUPLICATE_SIGNAL_RATE = 0.01;
export const SHADOW_PROMOTION_MIN_PAPER_FILL_RATE = 0.98;
export const SHADOW_PROMOTION_MIN_RETURN_FLOW_HIT_RATE = 0.90;
export const SHADOW_PROMOTION_MAX_DATA_CORRUPTION_RATE = 0.03;
export const STALE_PENDING_BUSINESS_DAYS = 2;
export const BLOCKED_LOOKUP_DAYS = [0, 1, 2, 3, 5] as const;
export const DEFAULT_MAX_LEDGER_ITEMS = 5_000;
