// @responsibility ADR-0487 fresh data supply diagnostic snapshot helpers; OBSERVE/SHADOW_ONLY only.
import type { InvestorFlowSampleAcquisitionReportAdr0489 } from './investorFlowSampleAcquisitionAdr0489.js';

export type FreshDataDomain = 'SECTOR_ENERGY' | 'SUPPLY' | 'PRICE_VOLUME' | 'PROGRAM_TRADING' | 'SHORT_CREDIT' | 'MACRO' | 'FUNDAMENTAL' | 'UNKNOWN';
export type FreshDataProvider = 'KRX' | 'KIS' | 'NAVER' | 'FSS' | 'DART' | 'YAHOO' | 'CACHE' | 'INTERNAL' | 'UNKNOWN';
export type FreshDataStage = 'OBSERVE' | 'SHADOW_ONLY';
export type FreshDataLineStatus = 'NOT_STARTED' | 'OBSERVING' | 'FETCH_OK' | 'NORMALIZED' | 'PARTIAL' | 'STALE' | 'MISSING' | 'DATA_UNAVAILABLE' | 'PROVIDER_ERROR' | 'CACHE_ONLY' | 'READY_FOR_SHADOW' | 'UNKNOWN';
export type FreshDataSourceState = 'FRESH' | 'STALE' | 'MISSING' | 'EMPTY' | 'DATA_UNAVAILABLE' | 'PROVIDER_ERROR' | 'NON_TRADING_DAY' | 'UNKNOWN';
export type FreshDataCacheState = 'FRESH' | 'STALE' | 'EMPTY' | 'MISSING' | 'UNKNOWN';
export interface FreshDataSnapshotAdr0487 { sourceId: string; domain: FreshDataDomain; provider: FreshDataProvider; stage: FreshDataStage; collectedAt: string; sourceDate: string | null; cacheState: FreshDataCacheState; sourceState: FreshDataSourceState; cacheAgeMinutes: number | null; sourceAgeTradingDays: number | null; coverageRatio: number; normalized: boolean; status: FreshDataLineStatus; confidence: 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE'; isProviderIssue: boolean; isMarketSignal: false; executionImpact: 'NONE'; liveExecutionAllowed: false; operatorApprovalRequired: true; diagnostics: string[]; }
function providerFromProbe(provider: string): FreshDataProvider { if (provider === 'NAVER') return 'NAVER'; if (provider === 'KIS') return 'KIS'; if (provider === 'KRX') return 'KRX'; if (provider === 'CACHE') return 'CACHE'; if (provider === 'INTERNAL_REPLAY') return 'INTERNAL'; return 'UNKNOWN'; }
function statusFromProbe(status: InvestorFlowSampleAcquisitionReportAdr0489['overallStatus'], stage: FreshDataStage): FreshDataLineStatus { if (status === 'SAMPLE_ACQUIRED') return stage === 'SHADOW_ONLY' ? 'READY_FOR_SHADOW' : 'NORMALIZED'; if (status === 'SAMPLE_PARTIAL') return 'PARTIAL'; if (status === 'SAMPLE_EMPTY') return 'MISSING'; if (status === 'DATA_UNAVAILABLE') return 'DATA_UNAVAILABLE'; if (status === 'PROVIDER_ERROR' || status === 'PARSE_ERROR' || status === 'RATE_LIMITED') return 'PROVIDER_ERROR'; if (status === 'SAMPLE_STALE') return 'STALE'; return 'OBSERVING'; }
export function buildFreshDataInvestorFlowProbeSnapshotAdr0487(report: InvestorFlowSampleAcquisitionReportAdr0489): FreshDataSnapshotAdr0487 {
  const selected = report.selectedSample;
  return { sourceId: 'INVESTOR_FLOW_SAMPLE_PROBE', domain: 'SUPPLY', provider: providerFromProbe(report.selectedProvider), stage: report.stage, collectedAt: report.generatedAt, sourceDate: selected?.sourceDate ?? null, cacheState: report.attempts.some((attempt) => attempt.cacheHit) ? 'FRESH' : 'UNKNOWN', sourceState: selected ? selected.freshness.sourceState : report.overallStatus === 'DATA_UNAVAILABLE' ? 'DATA_UNAVAILABLE' : report.overallStatus === 'PROVIDER_ERROR' ? 'PROVIDER_ERROR' : 'MISSING', cacheAgeMinutes: null, sourceAgeTradingDays: selected?.freshness.sampleAgeTradingDays ?? null, coverageRatio: report.coverageRatio, normalized: Boolean(selected), status: statusFromProbe(report.overallStatus, report.stage), confidence: selected?.confidence ?? 'NONE', isProviderIssue: !report.sampleAcquired, isMarketSignal: false, executionImpact: 'NONE', liveExecutionAllowed: false, operatorApprovalRequired: true, diagnostics: ['ADR-0487 includes ADR-0489 investor-flow sample probe as diagnostic fresh-data evidence only.', ...report.diagnostics] };
}
export function formatRuntimePipelineFreshDataSupplyEvidenceLineAdr0487(snapshot: FreshDataSnapshotAdr0487 | null | undefined): string { return snapshot ? `ADR-0487 freshDataSupply source=${snapshot.sourceId} status=${snapshot.status} diagnosticOnly=true executionImpact=${snapshot.executionImpact}` : 'ADR-0487 freshDataSupply=missing diagnosticOnly=true executionImpact=NONE'; }
