import fs from 'fs';
import { describe, expect, it } from 'vitest';
import { buildInvestorFlowProviderRouteFromProbeAdr0489, buildInvestorFlowProbeObservationRowAdr0489, buildInvestorFlowSampleAcquisitionReportAdr0489, formatInvestorFlowSampleProbeCompactAdr0489, formatInvestorFlowSampleProbeDetailAdr0489, formatRuntimePipelineInvestorFlowProbeEvidenceLineAdr0489, getInvestorFlowSampleProbeDetailRegistryEntryAdr0489 } from './investorFlowSampleAcquisitionAdr0489.js';
import { buildFreshDataInvestorFlowProbeSnapshotAdr0487 } from './freshDataSupplyLayerAdr0487.js';
import { buildSupplyCoverageSnapshotAdr0484 } from './supplyCoverageRecoveryObservationAdr0484.js';
import { buildSupplyAdvisoryReadinessReportAdr0485 } from './supplyAdvisoryReadinessAdr0485.js';
import { buildOperatorActionQueueAdr0480 } from './operatorActionRouterAdr0480.js';

const generatedAt = '2026-05-09T00:00:00.000Z';
const sample = (provider: 'CACHE' | 'KIS' | 'KRX' | 'INTERNAL_REPLAY' = 'CACHE', overrides = {}) => ({ provider, sourceDate: '2026-05-08', collectedAt: generatedAt, foreignNetBuy: 100, institutionNetBuy: 50, programNetBuy: 0, individualNetBuy: -150, unit: 'KRW' as const, status: 'VERIFIED', sourceAgeTradingDays: 0, providerSemanticCapable: true, ...overrides });
const naverCollector = (status: any = 'DATA_AVAILABLE', overrides = {}) => ({ code: '005930', provider: 'NAVER' as const, status, signal: 'BULLISH' as const, points: [], latestPoint: { date: '2026-05-08', foreignNetBuy: 100, institutionNetBuy: 50, programNetBuy: 0, individualNetBuy: -150, source: 'NAVER' as const, confidence: 'HIGH' as const }, coverage: { availableDays: 1, requestedDays: 5, foreignAvailable: 1, institutionAvailable: 1, programAvailable: 1 }, freshness: { sourceState: 'FRESH' as const, lastSourceDate: '2026-05-08', sourceAgeTradingDays: 0 }, semanticNetBuyCandidate: { foreignNetBuy: 100, institutionNetBuy: 50, programNetBuy: 0, sourceDate: '2026-05-08', confidence: 'HIGH' as const, status: 'VERIFIED' as const, signal: 'BULLISH' as const }, executionImpact: 'NONE' as const, liveExecutionAllowed: false as const, policyPromotionMode: 'SHADOW_ONLY' as const, operatorApprovalRequired: true as const, diagnostics: [], ...overrides });

describe('ADR-0489 Investor Flow Sample Acquisition Probe', () => {
  it('1. NAVER successful normalized sample returns SAMPLE_ACQUIRED.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, naverCollectorAdr0481: naverCollector() }); expect(report.overallStatus).toBe('SAMPLE_ACQUIRED'); expect(report.selectedProvider).toBe('NAVER'); });
  it('2. NAVER empty sample returns SAMPLE_EMPTY and UNKNOWN.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, naverCollectorAdr0481: naverCollector('EMPTY', { semanticNetBuyCandidate: null, latestPoint: null }) }); expect(report.attempts[0].status).toBe('SAMPLE_EMPTY'); expect(report.attempts[0].signal).toBe('UNKNOWN'); });
  it('3. NAVER provider error returns PROVIDER_ERROR and UNKNOWN.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, naverCollectorAdr0481: naverCollector('PROVIDER_ERROR', { semanticNetBuyCandidate: null }) }); expect(report.attempts[0].status).toBe('PROVIDER_ERROR'); expect(report.attempts[0].signal).toBe('UNKNOWN'); });
  it('4. CACHE valid sample can be selected if NAVER unavailable.', () => { expect(buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, cacheSample: sample('CACHE') }).selectedProvider).toBe('CACHE'); });
  it('5. KIS provider mismatch is not selected and not bearish.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, kisSample: sample('KIS', { providerSemanticCapable: false }) }); const kis = report.attempts.find((a) => a.provider === 'KIS')!; expect(kis.status).toBe('PROVIDER_MISMATCH'); expect(kis.signal).toBe('UNKNOWN'); expect(kis.marketSignal).toBe(false); expect(report.selectedProvider).toBe('NONE'); });
  it('6. KRX unavailable returns DATA_UNAVAILABLE and UNKNOWN.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, krxSample: sample('KRX', { status: 'DATA_UNAVAILABLE', foreignNetBuy: null, institutionNetBuy: null }) }); const krx = report.attempts.find((a) => a.provider === 'KRX')!; expect(krx.status).toBe('DATA_UNAVAILABLE'); expect(krx.signal).toBe('UNKNOWN'); });
  it('7. INTERNAL_REPLAY sample can be used only as OBSERVE/SHADOW_ONLY.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt, stage: 'OBSERVE', internalReplaySample: sample('INTERNAL_REPLAY') }); expect(report.selectedProvider).toBe('INTERNAL_REPLAY'); expect(report.policyPromotionMode).toBe('OBSERVE'); });
  it('8-9. selectedProvider=NONE and sampleAcquired=false when all attempts fail.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ code: '005930', generatedAt }); expect(report.selectedProvider).toBe('NONE'); expect(report.sampleAcquired).toBe(false); });
  it('10-14. Missing/provider/rate/non-trading states remain non-live UNKNOWN, not bearish.', () => { const providerError = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample('CACHE', { status: 'PROVIDER_ERROR' }) }); expect(providerError.attempts.every((a) => a.providerIssue ? a.signal !== 'BEARISH' : true)).toBe(true); const nonTrading = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, nonTradingDay: true, naverCollectorAdr0481: naverCollector() }); expect(nonTrading.overallStatus).toBe('NON_TRADING_DAY'); const limited = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample(), rateLimitedProviders: ['CACHE'] }); expect(limited.attempts.find((a) => a.provider === 'CACHE')?.status).toBe('RATE_LIMITED'); expect(limited.attempts.find((a) => a.provider === 'CACHE')?.signal).toBe('UNKNOWN'); expect(providerError.liveExecutionAllowed).toBe(false); });
  it('15-18. Valid signals require normalized HIGH/MEDIUM confidence; stale sample is not selected.', () => { const bull = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample('CACHE', { foreignNetBuy: 100, institutionNetBuy: 50 }) }); const bear = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample('CACHE', { foreignNetBuy: -100, institutionNetBuy: -50 }) }); const partial = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, stage: 'SHADOW_ONLY', cacheSample: sample('CACHE', { status: 'PARTIAL', institutionNetBuy: null }) }); const stale = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample('CACHE', { sourceAgeTradingDays: 5 }) }); expect(bull.selectedSample?.signal).toBe('BULLISH'); expect(bear.selectedSample?.signal).toBe('BEARISH'); expect(partial.selectedProvider).toBe('CACHE'); expect(stale.selectedProvider).toBe('NONE'); });
  it('19-27. Wiring helpers expose router/fresh-data/coverage/readiness/action/ledger/compact/detail/runtime evidence.', () => { const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, cacheSample: sample() }); expect(buildInvestorFlowProviderRouteFromProbeAdr0489(report).selectedProvider).toBe('CACHE'); expect(buildFreshDataInvestorFlowProbeSnapshotAdr0487(report).sourceId).toBe('INVESTOR_FLOW_SAMPLE_PROBE'); expect(buildSupplyCoverageSnapshotAdr0484({ investorFlowSampleAcquisitionAdr0489: report }).semanticNetBuy.sampleAvailableCount).toBeGreaterThan(0); expect(buildSupplyAdvisoryReadinessReportAdr0485({ investorFlowSampleAcquisitionAdr0489: report }).policyPromotionMode).toBe('SHADOW_ONLY'); expect(buildOperatorActionQueueAdr0480({ investorFlowSampleAcquisitionAdr0489: buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt }) }).dedupedRootCauses).toContain('INVESTOR_FLOW_SAMPLE_ACQUISITION_NEEDED'); expect(buildInvestorFlowProbeObservationRowAdr0489(report).observationType).toBe('INVESTOR_FLOW_SAMPLE_ACQUISITION_ADR0489'); expect(formatInvestorFlowSampleProbeCompactAdr0489(report)).toContain('ADR-0489 InvestorFlowProbe'); expect(getInvestorFlowSampleProbeDetailRegistryEntryAdr0489(report).adrTraceHint).toBe('/adr_trace 0489'); expect(formatRuntimePipelineInvestorFlowProbeEvidenceLineAdr0489(report)).toContain('ADR-0489'); });
  it('28-37. Static safety guards remain in force and failures are isolated.', () => { const src = fs.readFileSync('server/trading/signalScanner/investorFlowSampleAcquisitionAdr0489.ts', 'utf8'); expect(src).not.toMatch(/rawPayload|save.*raw|persist.*raw/i); expect(src).not.toMatch(/kisOrder|orderExecutor|trancheExecutor|autoTradeEngine|createLiveOrder/i); expect(src).not.toMatch(/setGateThreshold|kelly|STRONG_BUY|gateWeight/i); const row = buildInvestorFlowProbeObservationRowAdr0489(buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt })); expect(row.requiredScore).toBe(70); const report = buildInvestorFlowSampleAcquisitionReportAdr0489({ generatedAt, stage: 'OBSERVE', cacheSample: { provider: 'CACHE', foreignNetBuy: Symbol('bad') as any } as any }); expect(report.executionImpact).toBe('NONE'); expect(report.liveExecutionAllowed).toBe(false); expect(['OBSERVE', 'SHADOW_ONLY']).toContain(report.policyPromotionMode); expect(report.operatorApprovalRequired).toBe(true); expect(formatInvestorFlowSampleProbeDetailAdr0489(report)).toContain('guardrails'); });
});
