/**
 * @responsibility PersistScanResults dependency re-export surface.
 * ADR-0001 scan diagnostics core split.
 */

export { sendTelegramAlert } from '../../../alerts/telegramClient.js';
export { getNoiseCounters, logNoiseDetail, logNoiseSummary } from '../../../utils/logger.js';
export { buildEmptyScanRootCauseEventsFromStringsAdr0500, safeBuildEmptyScanRootCauseDashboardAdr0500 } from '../../../diagnostics/emptyScanRootCauseDashboardAdr0500.js';
export { buildWeekendReplayRecordsFromStringsAdr0501, safeBuildWeekendReplaySummaryAdr0501 } from '../../../diagnostics/weekendReplayAdr0501.js';
export { appendScanTraces } from '../../scanTracer.js';
export { classifyEmptyScanReason, describeEmptyScanReason } from '../emptyScanClassifier.js';
export { evaluateR3Sanity } from '../r3SanityCheck.js';
export { activateR3SanityBlock } from '../../../persistence/r3SanityBlockRepo.js';
export { evaluateR3ViolationState } from '../r3ViolationStateMachine.js';
export { clearPreflightBlockedScanSummary } from '../preflightBlockedScanSummary.js';
export { buildR3NoiseDecision } from '../r3NoiseGovernorWiring.js';
export { summarizePreBreakoutWaitDecisions } from '../preBreakoutWaitPolicy.js';
export { buildFreshScanBlockerAttribution } from '../freshScanBlockerAttribution.js';
export { buildGate2FreshAttribution, buildSectorEnergyDiagnostic } from '../gate2LeadershipAttribution.js';
export { buildGate1MinimumSignalForensicAuditAdr0505, buildGate1MinimumSignalForensicSummaryAdr0505, isGate1MinimumSignalForensicAuditDisabled, resolveGate1EvaluationStateAdr0510 } from '../gate1MinimumSignalForensicAuditAdr0505.js';
export { appendGate1ForensicTrace } from '../../../persistence/gate1MinimumSignalForensicTraceRepo.js';
export { collectGate1ForensicInputsFromEntryFilterDecompositionAdr0507 } from '../gate1ForensicInputsCollectorAdr0507.js';
export { deriveGateDecisionRouterResult } from '../gateDecisionRouter.js';
export { summarizeProvisionalShadowCandidates } from '../provisionalShadowLane.js';
export { summarizeCounterfactualShadowLearningCandidates } from '../counterfactualShadowLearningLane.js';
export { buildGateReclassificationDryRunSummary } from '../../../learning/gateReclassificationDryRun.js';
export { buildEntryFilterDecomposition } from '../entryFilterDecomposition.js';
export { buildPositiveScoreStarvationFallbackReport, buildPositiveScoreStarvationReport } from '../gate1PositiveScoreStarvation.js';
export { buildGate1ScoreCeilingRepairReport } from '../gate1ScoreCeilingRepair.js';
export { buildPenaltyDeduplicationReport } from '../gate1PenaltyDeduplication.js';
export { buildRiskDoubleCountAuditReport } from '../gate1RiskDoubleCount.js';
export { buildFinalGate1CalibrationAuditReport } from '../gate1FinalCalibration.js';
export { buildGate1ScoringAlignmentReport } from '../gate1ScoringAlignmentAdr0472.js';
export { buildGate1ScoringAlignmentDryRunGate } from '../gate1ScoringAlignmentDryRunGateAdr0520.js';
export { buildGate1PositiveSourceWiringReport } from '../gate1PositiveSourceWiringAdr0475.js';
export { buildGate1DryRunObservationRows, saveGate1DryRunObservationRows, summarizeGate1DryRunObservationRows } from '../gate1DryRunObservationLedgerAdr0476.js';
export { buildInvestorFlowProviderRouteResultAdr0477 } from '../investorFlowProviderRouterAdr0477.js';
export { buildNaverInvestorTrendCollectorResultAdr0481, collectNaverInvestorTrendCollectorResultAdr0481 } from '../naverInvestorTrendCollectorAdr0481.js';
export { buildSemanticNetBuyNormalizationReportAdr0482 } from '../semanticNetBuyNormalizerAdr0482.js';
export { buildSupplySourceFreshnessReportAdr0483 } from '../supplySourceFreshnessAdr0483.js';
export { buildSupplyCoverageRecoveryObservationReportAdr0484 } from '../supplyCoverageRecoveryObservationAdr0484.js';
export { buildSupplyAdvisoryReadinessReportAdr0485 } from '../supplyAdvisoryReadinessAdr0485.js';
export { buildSupplyRecoveryRuntimeMountReportAdr0486 } from '../supplyRecoveryRuntimeMountAdr0486.js';
export { buildFreshDataSupplyReportAdr0487 } from '../freshDataSupplyLayerAdr0487.js';
export { buildSectorEnergyAndSupplyUnknownPolicyReportAdr0488 } from '../sectorEnergyMasterSupplyUnknownPolicyAdr0488.js';
export { buildInvestorFlowSampleAcquisitionReportAdr0489 } from '../investorFlowSampleAcquisitionAdr0489.js';
export { recordSupplySnapshotAdr0491, readLatestSupplySnapshotBySymbolSourceDomainAdr0491 } from '../supplySnapshotStoreReplayAdr0491.js';
export { previousTradingDateCandidateAdr0491 } from '../investorFlowSnapshotKeyNormalizerAdr0491.js';
export { fetchKisInvestorFlowEvidence } from '../../../supply/kisInvestorFlowEvidence.js';
export { fetchInvestorFlowWithPolicy } from '../../../supply/investorFlowRouter.js';
export { rememberSupplyBySymbolPayloadSnapshot } from '../../../supply/investorFlowBySymbolPayloadSnapshot.js';
export { fetchInvestorTrading, getLastKrxInvestorTradingDiagnostic } from '../../../clients/krxClient.js';
export { DEFAULT_DATA_PROMOTION_STATUS } from './scanSummaryTypes.js';
export { buildGatePassDistribution, buildWaitDistribution } from './scanCounterAccumulators.js';
export { buildGateScoreCandidateBucketSummary, buildGateScoreHealthSummary } from './gateScoreDiagnostics.js';
export { buildGateDiagnosticCarrySummary, buildGateLayerAuditSummary } from './gateLayerDiagnostics.js';
export { buildPerStageDropoffSummary } from './pipelineStageDiagnostics.js';
export { cacheRawToNaverInvestorTrendPointAdr0481, cacheRawToSemanticInputAdr0482 } from './supplyDiagnostics.js';
export { buildScanEvaluationResult } from '../state/scanEvaluationState.js';
export { emitScanDiagnosticBuildFailedWarn, emitScanEvaluationWarnings } from '../state/scanDiagnosticSuppressor.js';
export { recordScanCase } from '../state/scanCaseRecorder.js';
export { cacheLookupToSemanticInputAdr0482, compactTradingDateAdr0505, kisEvidenceToSemanticInputAdr0482, krxDiagnosticToRouterInputAdr0505, krxInvestorRowToRouterRawAdr0505, krxInvestorRowToSemanticInputAdr0482, normalizeSymbolCodeAdr0505, naverCollectorToSemanticInputAdr0482, resolveActualSymbolForAdr0477, routedKisFlowToAdr0477Raw, routedKisFlowToSemanticInputAdr0482 } from './investorFlowAdapters.js';
export { logAdrDiagnostic, logGateDiagnosticSummary, logPreBreakoutNoiseSummary } from './adrDiagnosticLogger.js';
export { emitInvestorFlowRouterEventAdr0477 } from './investorFlowRouterEmitter.js';
export { formatR3StateMessage } from './sectionFormatters.js';
export { buildCandidatePool } from '../../candidatePoolBuilder.js';
export type { ShadowCandidateScanTrigger } from '../../marketStateResolver.js';
export type { FrozenQuoteResult } from '../frozenQuoteDetector.js';
export type { StreakSkipReason } from '../r3StreakSkipPolicy.js';
export type { SectorEnergyQualityDiagnostic } from '../../../clients/sectorEnergyQualityDiagnostic.js';
export type { ProvisionalShadowSectionInput } from '../provisionalShadowLane.js';
export type { CounterfactualShadowSectionInput } from '../counterfactualShadowLearningLane.js';
export type { CandidateSnapshot } from '../entryFilterDecomposition.js';
export type { InvestorFlowProviderRouterInput } from '../investorFlowProviderRouterAdr0477.js';
export type { PerSymbolSupplyInjectionStats } from '../injectPerSymbolSupplyContext.js';
export type { SemanticNetBuyInputPoint } from '../semanticNetBuyNormalizerAdr0482.js';
export type { FreshDataSupplyReportInputAdr0487 } from '../freshDataSupplyLayerAdr0487.js';
export type { MacroGateState, ScanSummary } from './scanSummaryTypes.js';
export type { ScanCounters } from './scanCounterTypes.js';
export type { ScanEvaluationResult } from '../state/scanEvaluationState.js';
export type { CandidatePoolInputCandidate, CandidatePoolResult } from '../../candidatePoolBuilder.js';
