// @responsibility Scan counter default construction.

import type { ScanCounters } from './scanCounterTypes.js';
import { createGateLayerAuditAccumulator } from './gateLayerDiagnostics.js';

export function createScanCounters(): ScanCounters {
  return {
    yahooFails: 0,
    gateMisses: 0,
    rrrMisses: 0,
    entries: 0,
    counterfactualRecordedToday: 0,
    pendingTraces: [],
    waitDataHold: 0,
    waitPreBreakout: 0,
    waitGateFail: 0,
    waitSizingBlocked: 0,
    waitDriftRemove: 0,
    waitDriftCorpAction: 0,
    waitVolumeDrop: 0,
    waitOther: 0,
    waitTierRestSuppressed: 0,
    gate1Pass: 0,
    gate1Unknown: 0,
    gate2Pass: 0,
    gate3Pass: 0,
    lastTriggerPass: 0,
    freshConditionBuckets: new Map(),
    gate2ConditionBuckets: new Map(),
    counterfactualShadowEligible: 0,
    counterfactualShadowCreated: 0,
    counterfactualShadowSkipped: 0,
    counterfactualShadowSkipReasons: {},
    counterfactualShadowCandidates: [],
    provisionalShadowEligible: 0,
    provisionalShadowCreated: 0,
    provisionalShadowSkipped: 0,
    provisionalShadowSkipReasons: {},
    provisionalShadowCandidates: [],
    liveEligibleCount: 0,
    shadowObservableCount: 0,
    dataUnavailableBlockedCount: 0,
    providerDegradedObservableCount: 0,
    trueGateFailCount: 0,
    hardRiskBlockedCount: 0,
    preBreakoutWaitDecisions: [],
    preBreakoutPriceDistance: 0,
    shadowNearBreakoutCreated: 0,
    shadowNearBreakoutBlocked: 0,
    shadowNearBreakoutBlockReasons: {},
    gateScoreHealthSamples: 0,
    gateScoreRawSum: 0,
    gateScoreAvailableMaxSum: 0,
    gateScoreNormalizedSum: 0,
    gateScoreUnavailableCounts: {},
    gateScoreThresholdNotMetCounts: {},
    gateScoreProviderDegradedCounts: {},
    gateLayerAudit: createGateLayerAuditAccumulator(),
    perStageDropoff: {},
    gateScoreBucketCounts: {
      EXECUTABLE: 0,
      DATA_BLOCKED_NEAR_MISS: 0,
      PROBING: 0,
      SHADOW_ONLY: 0,
      REJECTED: 0,
    },
    gateScoreBucketReasonCounts: {},
    dataBlockedNearMissUnavailableCounts: {},
    probingConditionCounts: {},
    nearMissOutcomeLedgerRecorded: 0,
    nearMissOutcomeLedgerSkipped: 0,
    entryCandidateSnapshots: [],
    gateReclassificationDryRunResults: [],
    positiveScoreStarvationTraces: [],
  };
}
