// @responsibility learning repair Telegram commands — virtual-only repair controls
import { commandRegistry } from '../../commandRegistry.js';
import type { TelegramCommand } from '../_types.js';
import { runGhostCloseResolver } from '../../../learning/ghostCloseResolver.js';
import { runAttributionBackfill } from '../../../learning/attributionBackfillEngine.js';
import { runSuggestThresholdCalibrator } from '../../../learning/suggestThresholdCalibrator.js';
import { scheduleGeminiLearningReflection } from '../../../learning/geminiUtilizationScheduler.js';
import { learningRepairDryRun, learningRepairRun, formatDryRunMessage, formatRunMessage } from '../../../learning/learningRepairCommand.js';
import { collectLearningOutcomeSummary, collectLearningOpenResidue, collectLearningQuarantineReport, collectLearningAttributionQuality, collectLearningSuggestReport, collectLearningConditionReport, formatLearningOutcomeSummary, formatLearningOpenResidue, formatLearningQuarantineReport, formatLearningAttributionQuality, formatLearningSuggestReport, formatLearningConditionReport } from '../../../learning/learningOutcomeQuality.js';
import { collectLearningCohortSummary, learningCohortBackfillRun, learningMetadataRepairDryRun, learningMetadataRepairRun, counterfactualBuildDryRun, counterfactualBuildRun, collectCounterfactualStatus, counterfactualResolveDryRun, counterfactualResolveRun, collectLearningHoldingOutliers, formatLearningCohortSummary, formatMetadataRepairDryRun, formatMetadataRepairRun, formatCounterfactualBuild, formatCounterfactualResolve, formatLearningHoldingOutliers } from '../../../learning/learningSampleQuality.js';
const cmds: TelegramCommand[] = [
  { name: '/learning_repair_dryrun', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '학습 루프 repair dry-run (데이터 변경 없음)', async execute({ reply }) { reply(formatDryRunMessage(await learningRepairDryRun())); } },
  { name: '/learning_repair_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '학습 루프 repair 실행 (실거래 영향 없음)', async execute({ reply }) { reply(formatRunMessage(await learningRepairRun())); } },
  { name: '/learning_outcome_summary', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '닫힌 학습 outcome 품질 요약 (read-only)', async execute({ reply }) { reply(formatLearningOutcomeSummary(collectLearningOutcomeSummary())); } },
  { name: '/learning_open_residue', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '남은 OPEN 학습 case 미종결 사유 분석', async execute({ reply }) { reply(formatLearningOpenResidue(collectLearningOpenResidue())); } },
  { name: '/learning_quarantine_report', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '격리 학습 case 원인/recovery 보고', async execute({ reply }) { reply(formatLearningQuarantineReport(collectLearningQuarantineReport())); } },
  { name: '/learning_attribution_quality', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '귀인 샘플 조건 커버리지/overfit 점검', async execute({ reply }) { reply(formatLearningAttributionQuality(collectLearningAttributionQuality())); } },
  { name: '/learning_suggest_report', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'diagnostic suggest proposal 보고 (autoApply=false)', async execute({ reply }) { reply(formatLearningSuggestReport(collectLearningSuggestReport())); } },
  { name: '/learning_cohort_summary', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: '학습 샘플 cohort 분리 요약 (promotion fresh-only)', async execute({ reply }) { reply(formatLearningCohortSummary(collectLearningCohortSummary())); } },
  { name: '/learning_cohort_backfill_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'cohortType truth backfill (metadata-only, executionImpact=NONE)', async execute({ reply }) { const r = learningCohortBackfillRun(); reply(`🧱 learning_cohort_backfill_run scanned=${r.scanned} updated=${r.updated} before=${JSON.stringify(r.before)} after=${JSON.stringify(r.after)} executionImpact=${r.executionImpact} brokerOrdersCreated=${r.brokerOrdersCreated} promotionAllowed=${r.promotionAllowed}`); } },
  { name: '/learning_metadata_repair_dryrun', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'metadata recovery 가능성 dry-run (no-write)', async execute({ reply }) { reply(formatMetadataRepairDryRun(learningMetadataRepairDryRun())); } },
  { name: '/learning_metadata_repair_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'metadata recovery 실행 (executionImpact=NONE)', async execute({ reply }) { reply(formatMetadataRepairRun(learningMetadataRepairRun())); } },
  { name: '/counterfactual_build_dryrun', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'counterfactual input build dry-run', async execute({ reply }) { reply(formatCounterfactualBuild(counterfactualBuildDryRun(), 'counterfactual_build_dryrun')); } },
  { name: '/counterfactual_build_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'counterfactual input build 실행 (no live impact)', async execute({ reply }) { reply(formatCounterfactualBuild(counterfactualBuildRun(), 'counterfactual_build_run')); } },
  { name: '/counterfactual_status', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'counterfactual sample 상태', async execute({ reply }) { reply(formatCounterfactualBuild(collectCounterfactualStatus(), 'counterfactual_status')); } },
  { name: '/counterfactual_resolve_dryrun', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'counterfactual outcome resolve dry-run (no-write)', async execute({ reply }) { reply(formatCounterfactualResolve(counterfactualResolveDryRun(), 'counterfactual_resolve_dryrun')); } },
  { name: '/counterfactual_resolve_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'counterfactual outcome resolve 실행 (executionImpact=NONE)', async execute({ reply }) { reply(formatCounterfactualResolve(counterfactualResolveRun(), 'counterfactual_resolve_run')); } },
  { name: '/learning_condition_report', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'condition min-sample/overfit guard 보고', async execute({ reply }) { reply(formatLearningConditionReport(collectLearningConditionReport())); } },
  { name: '/learning_holding_outliers', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'holding time outlier promotion 제외 보고', async execute({ reply }) { reply(formatLearningHoldingOutliers(collectLearningHoldingOutliers())); } },
  { name: '/ghost_close_status', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'Ghost close resolver dry-run 상태', async execute({ reply }) { const r = await runGhostCloseResolver({ dryRun: true }); reply(`👻 ghost_close_status scanned=${r.candidatesScanned} closeCandidates=${r.closed} pendingRetry=${r.pendingRetry} quarantined=${r.quarantined} executionImpact=NONE brokerOrdersCreated=${r.brokerOrdersCreated}`); } },
  { name: '/ghost_close_run', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'OPEN ghost case virtual close 실행', async execute({ reply }) { const r = await runGhostCloseResolver(); reply(`👻 ghost_close_run scanned=${r.candidatesScanned} closed=${r.closed} pendingRetry=${r.pendingRetry} quarantined=${r.quarantined} executionImpact=NONE brokerOrdersCreated=${r.brokerOrdersCreated}`); } },
  { name: '/attribution_backfill', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'closed but not attributed backfill', async execute({ reply }) { const r = runAttributionBackfill(); reply(`🧬 attribution_backfill processed=${r.processedCount} skipped=${r.skippedCount} samples7d=${r.attributionSamples7d}/${r.targetSampleCount} starvation=${r.starvationFlag} skipReason=${JSON.stringify(r.skipReasons)}`); } },
  { name: '/suggest_diagnostics', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'Suggest silence 진단 및 proposal 생성', async execute({ reply }) { const r = runSuggestThresholdCalibrator({ suggest7d: { counterfactual: 0, ledger: 0, kellySurface: 0, regime: 0 } }); reply(`💡 suggest_diagnostics blocker=${r.blocker} proposals=${r.proposals.length} autoApply=false\n${r.proposals.map(p => `${p.channel}: score=${p.observedScore}/${p.currentThreshold} sample=${p.sampleSize}`).join('\n')}`); } },
  { name: '/gemini_learning_status', category: 'LRN', visibility: 'ADMIN', riskLevel: 0, description: 'Gemini learning reflection 호출률/예약 상태', async execute({ reply }) { const r = scheduleGeminiLearningReflection(); reply(`♊ gemini_learning_status callsThisMonth=${r.callsThisMonth}/${r.tradingDaysThisMonth} utilizationRate=${(r.utilizationRate*100).toFixed(0)}% lastCallAt=${r.lastCallAt ?? 'N/A'} nextScheduledAt=${r.nextScheduledAt ?? 'N/A'} diagnostic=${r.diagnostic} recommendationOnly=${r.recommendationOnly}`); } },
];
for (const c of cmds) commandRegistry.register(c);
export default cmds;
