import type { AutoTradingDashboardState } from './autoTradingTypes';

export async function fetchAutoTradingDashboard(): Promise<AutoTradingDashboardState> {
  return {
    control: {
      mode: 'SHADOW',
      engineStatus: 'RUNNING',
      brokerConnected: true,
      lastScanAt: '2026-04-18 09:18:10',
      lastOrderAt: '2026-04-18 09:15:42',
      todayOrderCount: 4,
      todayPnL: 182000,
    },
    orders: [
      {
        id: 'order-1',
        symbol: '329180',
        name: 'HD현대중공업',
        side: 'BUY',
        quantity: 10,
        orderPrice: 245000,
        filledPrice: 244800,
        status: 'FILLED',
        createdAt: '09:15:42',
        brokerLatencyMs: 82,
      },
      {
        id: 'order-2',
        symbol: '042660',
        name: '한화오션',
        side: 'BUY',
        quantity: 15,
        orderPrice: 33600,
        status: 'REJECTED',
        createdAt: '09:16:30',
        failureReason: '주문 가능 수량 부족',
        brokerLatencyMs: 125,
      },
    ],
    positions: [
      {
        id: 'pos-1',
        symbol: '329180',
        name: 'HD현대중공업',
        enteredAt: '2026-04-18 09:15:42',
        entryReason: 'Gate 통과 + 거래량 동반 돌파',
        avgPrice: 244800,
        currentPrice: 251300,
        quantity: 10,
        pnlPct: 2.65,
        stopLossPrice: 234500,
        targetPrice1: 258000,
        targetPrice2: 267000,
        trailingStopEnabled: true,
        status: 'HOLD',
      },
    ],
    riskRules: [
      {
        id: 'risk-1',
        name: '일일 최대 손실 제한',
        enabled: true,
        triggered: false,
        message: '손실 한도 미도달',
      },
      {
        id: 'risk-2',
        name: 'VKOSPI 급등 시 신규매수 차단',
        enabled: true,
        triggered: true,
        message: '변동성 급등으로 신규매수 차단 중',
      },
    ],
    signals: [
      {
        id: 'sig-1',
        symbol: '329180',
        name: 'HD현대중공업',
        createdAt: '09:14:50',
        grade: 'STRONG_BUY',
        gate1Passed: 5,
        gate2Passed: 10,
        gate3Passed: 8,
        rrr: 2.8,
        status: 'FILLED',
      },
      {
        id: 'sig-2',
        symbol: '042660',
        name: '한화오션',
        createdAt: '09:16:12',
        grade: 'BUY',
        gate1Passed: 5,
        gate2Passed: 9,
        gate3Passed: 6,
        rrr: 2.1,
        status: 'BLOCKED',
        blockedReason: '리스크 룰에 의해 신규매수 차단',
      },
    ],
    logs: [
      {
        id: 'log-1',
        level: 'INFO',
        message: '신호 스캔 완료',
        createdAt: '09:14:40',
      },
      {
        id: 'log-2',
        level: 'SUCCESS',
        message: 'HD현대중공업 주문 체결 완료',
        createdAt: '09:15:42',
      },
      {
        id: 'log-3',
        level: 'WARNING',
        message: 'VKOSPI 급등 감지, 신규매수 제한 적용',
        createdAt: '09:16:00',
      },
      {
        id: 'log-4',
        level: 'ERROR',
        message: '한화오션 주문 거부: 주문 가능 수량 부족',
        createdAt: '09:16:30',
      },
    ],
    broker: {
      brokerName: 'KIS',
      connected: true,
      accountMasked: '123-45-****',
      orderAvailable: true,
      balanceSyncedAt: '2026-04-18 09:19:10',
      quoteSyncedAt: '2026-04-18 09:19:12',
      lastError: '',
    },
    emergency: {
      newBuyBlocked: true,
      autoTradingPaused: false,
      positionManageOnly: false,
    },
  };
}
