export {
  useMacroEnvironment,
  useEconomicRegime,
  useExtendedRegime,
  useSmartMoney,
  useExportMomentum,
  useGeoRisk,
  useCreditSpreads,
  useGlobalCorrelation,
  useSupplyChain,
  useSectorOrders,
  useFinancialStress,
  useFomcSentiment,
  useAllGlobalIntel,
} from './useGlobalIntelQueries';
