#!/usr/bin/env node
/**
 * @responsibility ADR generator — issue next ADR file and update INDEX.md from the INDEX next-number SSOT.
 *
 * Governance-only helper. No runtime trading imports and no live execution side effects.
 *
 * Usage:
 *   node scripts/create_adr.js "ops status command" --domain operations
 *   npm run adr:new -- "ops status command" --domain operations
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ADR_DIR = join(ROOT, 'docs', 'adr');
const INDEX_PATH = join(ADR_DIR, 'INDEX.md');

function usage(exitCode = 1) {
  const text = [
    'Usage:',
    '  node scripts/create_adr.js "title" --domain <domain> [--status Proposed|Accepted] [--dry-run]',
    '',
    'Examples:',
    '  npm run adr:new -- "ops status command" --domain operations',
    '  npm run adr:new -- "data promotion guard" --domain governance --status Proposed',
  ].join('\n');
  (exitCode === 0 ? console.log : console.error)(text);
  process.exit(exitCode);
}

function parseArgs(argv) {
  const args = [...argv];
  if (args.includes('--help') || args.includes('-h')) usage(0);
  const dryRun = args.includes('--dry-run');
  const cleaned = args.filter((arg) => arg !== '--dry-run');
  const title = cleaned.find((arg) => !arg.startsWith('--'));
  const domainIdx = cleaned.indexOf('--domain');
  const statusIdx = cleaned.indexOf('--status');
  const domain = domainIdx >= 0 ? cleaned[domainIdx + 1] : undefined;
  const status = statusIdx >= 0 ? cleaned[statusIdx + 1] : 'Proposed';

  if (!title || !domain) usage(1);
  if (!['Proposed', 'Accepted', 'Superseded', 'Rejected'].includes(status)) {
    console.error(`Invalid --status: ${status}`);
    usage(1);
  }
  return { title, domain, status, dryRun };
}

function slugify(title) {
  const slug = String(title)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
  if (!slug || !/^[a-z0-9가-힣]/.test(slug)) {
    throw new Error(`Cannot derive ADR slug from title: ${title}`);
  }
  return slug;
}

function parseNextNumber(indexSrc) {
  const match = indexSrc.match(/\*\*다음 ADR 번호:\s*`(\d{4})`\*\*/);
  if (!match) throw new Error('INDEX.md next ADR number not found. Expected: **다음 ADR 번호: `NNNN`**');
  return match[1];
}

function incrementNumber(number) {
  return String(Number(number) + 1).padStart(4, '0');
}

function todayKst() {
  return new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

function escapeTableCell(value) {
  return String(value).replace(/\|/g, '/').trim();
}

function buildAdrBody({ number, title, domain, status }) {
  const safeTitle = escapeTableCell(title);
  const safeDomain = escapeTableCell(domain);
  return `# ADR-${number}: ${safeTitle}\n\n@responsibility ${safeDomain} — ${safeTitle}\n\n## Status\n\n${status}\n\n## Context\n\n-\n\n## Decision\n\n-\n\n## Consequences\n\n-\n\n## Guardrails\n\n- No live trading path change unless explicitly stated.\n- No KIS/order import or invocation unless explicitly stated.\n- No Gate/Kelly/STRONG_BUY behavior change unless explicitly stated.\n- No Shadow policy change unless explicitly stated.\n- No provider fetch behavior change unless explicitly stated.\n- No data promotion behavior change unless explicitly stated.\n`;
}

function updateIndex({ indexSrc, number, nextNumber, title, domain }) {
  const safeTitle = escapeTableCell(title);
  const safeDomain = escapeTableCell(domain);
  const date = todayKst();
  let updated = indexSrc.replace(
    /\*\*다음 ADR 번호:\s*`\d{4}`\*\*/,
    `**다음 ADR 번호: \`${nextNumber}\`**`,
  );

  const issuanceLine = `\n(${date} 기준, 마지막 발급 ${number} — ${slugify(title)}. ADR-${number} — ${safeTitle}. Generated by scripts/create_adr.js; fill Context/Decision/Consequences before merge.)\n`;
  const nextSectionMarker = /## 다음 발급\n\n\*\*다음 ADR 번호:\s*`\d{4}`\*\*/;
  const nextMatch = updated.match(nextSectionMarker);
  if (!nextMatch || nextMatch.index === undefined) {
    throw new Error('Cannot locate INDEX.md 다음 발급 section after next-number update.');
  }
  const insertAfter = nextMatch.index + nextMatch[0].length;
  updated = `${updated.slice(0, insertAfter)}${issuanceLine}${updated.slice(insertAfter)}`;

  const row = `| ${number} | ${safeTitle} | ${safeDomain} |`;
  const mainIndexHeader = '## 전체 인덱스';
  const mainIndexPos = updated.indexOf(mainIndexHeader);
  if (mainIndexPos === -1) {
    throw new Error('Cannot locate INDEX.md ## 전체 인덱스 section.');
  }
  const afterHeader = updated.indexOf('\n', mainIndexPos + mainIndexHeader.length);
  const tableSeparator = updated.indexOf('\n|', afterHeader + 1);
  const secondTableLine = updated.indexOf('\n', tableSeparator + 1);
  if (afterHeader === -1 || tableSeparator === -1 || secondTableLine === -1) {
    throw new Error('Cannot locate INDEX.md 전체 인덱스 table header.');
  }
  updated = `${updated.slice(0, secondTableLine + 1)}${row}\n${updated.slice(secondTableLine + 1)}`;

  return updated;
}

function main() {
  const input = parseArgs(process.argv.slice(2));
  if (!existsSync(INDEX_PATH)) throw new Error(`INDEX.md not found: ${INDEX_PATH}`);
  const indexSrc = readFileSync(INDEX_PATH, 'utf-8');
  const number = parseNextNumber(indexSrc);
  const nextNumber = incrementNumber(number);
  const slug = slugify(input.title);
  const filename = `${number}-${slug}.md`;
  const filePath = join(ADR_DIR, filename);
  if (existsSync(filePath)) throw new Error(`ADR file already exists: ${filePath}`);

  const body = buildAdrBody({ number, title: input.title, domain: input.domain, status: input.status });
  const updatedIndex = updateIndex({ indexSrc, number, nextNumber, title: input.title, domain: input.domain });

  if (input.dryRun) {
    console.log(`[ADR New] dry-run number=${number} next=${nextNumber} file=docs/adr/${filename}`);
    console.log('--- ADR body preview ---');
    console.log(body);
    return;
  }

  writeFileSync(filePath, body, 'utf-8');
  writeFileSync(INDEX_PATH, updatedIndex, 'utf-8');
  console.log(`[ADR New] created docs/adr/${filename}`);
  console.log(`[ADR New] updated INDEX.md next number ${number} -> ${nextNumber}`);
  console.log('[ADR New] run: npm run validate:adrBaselinePolicy && npm run validate:adrIndex');
}

try {
  main();
} catch (error) {
  console.error(`[ADR New] FAIL — ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}
