/**
 * install_git_hooks.js
 *
 * .git/hooks/pre-commit 을 설치해 `npm run precommit` 을 호출하도록 한다.
 * 사용: npm run install:hooks
 */

import { writeFileSync, chmodSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const hookDir = '.git/hooks';
const hookFile = join(hookDir, 'pre-commit');

if (!existsSync('.git')) {
  console.error('[install:hooks] .git 디렉터리가 없습니다. git repo에서 실행하세요.');
  process.exit(1);
}
if (!existsSync(hookDir)) mkdirSync(hookDir, { recursive: true });

const script = `#!/bin/sh
# auto-generated by scripts/install_git_hooks.js
# 검증 실패 시 커밋 차단.
set -e
npm run precommit
`;

writeFileSync(hookFile, script);
chmodSync(hookFile, 0o755);
console.log(`[install:hooks] ${hookFile} 설치 완료 — 이후 git commit 시 자동 실행됩니다.`);
