/** @responsibility ADR-0493 stage-specific data promotion requirements. */
import type { DataLineStage, DataPromotionRequirements } from '../../types/dataPromotion.types';

const REQUIREMENTS: DataPromotionRequirements[] = [
  {
    currentStage: 'OBSERVE',
    requestedNextStage: 'SHADOW_RAW',
    minTradingDays: 0,
    maxMissingRate: null,
    maxStaleMisclassifications: null,
    minSnapshots: 1,
    requireProviderHealthField: true,
    requireFreshnessField: true,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: false,
    requirePositiveShadowContribution: false,
    requireStablePositiveShadowContribution: false,
    requireLiveRegression: false,
    requireNullZeroSeparation: false,
    requireHolidayFreshness: false,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: false,
    automaticPromotionAllowed: true,
    requiredScore: 40,
    description: 'Basic observed snapshots can enter raw shadow storage only when audit impact is none.',
  },
  {
    currentStage: 'SHADOW_RAW',
    requestedNextStage: 'SHADOW_SCORE',
    minTradingDays: 5,
    maxMissingRate: 0.20,
    maxStaleMisclassifications: null,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: true,
    requireProviderMarketSeparation: false,
    requirePositiveShadowContribution: false,
    requireStablePositiveShadowContribution: false,
    requireLiveRegression: false,
    requireNullZeroSeparation: true,
    requireHolidayFreshness: false,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: false,
    automaticPromotionAllowed: true,
    requiredScore: 60,
    description: 'Raw shadow data can be scored after minimum history, low missingness, null/zero separation, and replayable snapshots.',
  },
  {
    currentStage: 'SHADOW_SCORE',
    requestedNextStage: 'ADVISORY',
    minTradingDays: 10,
    maxMissingRate: 0.10,
    maxStaleMisclassifications: 3,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: true,
    requirePositiveShadowContribution: false,
    requireStablePositiveShadowContribution: false,
    requireLiveRegression: true,
    requireNullZeroSeparation: false,
    requireHolidayFreshness: false,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: false,
    automaticPromotionAllowed: true,
    requiredScore: 75,
    description: 'Scored shadow data can become advisory only after provider failures are separated from market signals and live regression passes.',
  },
  {
    currentStage: 'ADVISORY',
    requestedNextStage: 'WEIGHTED',
    minTradingDays: 20,
    maxMissingRate: 0.05,
    maxStaleMisclassifications: 2,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: false,
    requirePositiveShadowContribution: true,
    requireStablePositiveShadowContribution: false,
    requireLiveRegression: true,
    requireNullZeroSeparation: true,
    requireHolidayFreshness: true,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: true,
    automaticPromotionAllowed: true,
    requiredScore: 85,
    description: 'Advisory lines can receive weight only after longer history, very low data errors, positive contribution, and coverage checks.',
  },
  {
    currentStage: 'WEIGHTED',
    requestedNextStage: 'GATED',
    minTradingDays: 40,
    maxMissingRate: 0.03,
    maxStaleMisclassifications: 1,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: true,
    requirePositiveShadowContribution: true,
    requireStablePositiveShadowContribution: true,
    requireLiveRegression: true,
    requireNullZeroSeparation: false,
    requireHolidayFreshness: false,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: true,
    automaticPromotionAllowed: true,
    requiredScore: 92,
    description: 'Weighted lines can request gated usage only with long history, near-zero errors, stable contribution, and clean provider separation.',
  },
  {
    currentStage: 'GATED',
    requestedNextStage: 'CORE',
    minTradingDays: 0,
    maxMissingRate: 0,
    maxStaleMisclassifications: 0,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: true,
    requirePositiveShadowContribution: true,
    requireStablePositiveShadowContribution: true,
    requireLiveRegression: true,
    requireNullZeroSeparation: true,
    requireHolidayFreshness: true,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: true,
    automaticPromotionAllowed: false,
    requiredScore: 100,
    description: 'CORE promotion is intentionally not permitted by ADR-0493 without a separate ADR and explicit manual approval process.',
  },
];

export function getPromotionRequirements(currentStage: DataLineStage, requestedNextStage: DataLineStage): DataPromotionRequirements {
  const found = REQUIREMENTS.find((rule) => rule.currentStage === currentStage && rule.requestedNextStage === requestedNextStage);
  if (found) return found;
  return {
    currentStage,
    requestedNextStage,
    minTradingDays: Number.POSITIVE_INFINITY,
    maxMissingRate: 0,
    maxStaleMisclassifications: 0,
    minSnapshots: 1,
    requireProviderHealthField: false,
    requireFreshnessField: false,
    requireSnapshotRecordable: false,
    requireProviderMarketSeparation: true,
    requirePositiveShadowContribution: false,
    requireStablePositiveShadowContribution: false,
    requireLiveRegression: true,
    requireNullZeroSeparation: true,
    requireHolidayFreshness: true,
    requireExecutionImpactNonePassed: true,
    requireTestCoverage: true,
    automaticPromotionAllowed: false,
    requiredScore: 100,
    description: 'Unsupported promotion path is denied by default.',
  };
}

export function getAllPromotionRequirements(): readonly DataPromotionRequirements[] {
  return REQUIREMENTS;
}
