// @responsibility Shadow case data contracts with runtime SSOT provenance.
import type { EngineMode, ExecutionImpact } from '../../runtime/engineRuntimePolicy.js';
import type { RegimeConfidence, RegimePhase } from '../regimeContext.js';
import type { ShadowLifecycleState } from './lifecycle.js';
import type { OutcomeLabel } from './outcome.js';

export type DataHealth = 'OK' | 'STALE' | 'DEGRADED' | 'EMPTY' | 'CORRUPTED' | 'UNAVAILABLE';
export type ProviderHealth = 'OK' | 'KRX_UNAVAILABLE' | 'NAVER_NOT_WIRED' | 'CACHE_EMPTY' | 'PROVIDER_DEGRADED' | 'PROVIDER_ERROR';
export type ConfidenceLevel = 'VERIFIED' | 'CALCULATED' | 'FALLBACK' | 'AI_ESTIMATE' | 'LOW' | 'QUARANTINED';
export type SourceConfidence = 'VERIFIED' | 'CALCULATED' | 'EXTERNAL_API' | 'FALLBACK' | 'AI_ESTIMATE' | 'UNKNOWN';

export interface ShadowCase {
  caseId: string;
  signalId: string;
  symbol: string;
  symbolName: string;
  detectedAt: string;
  marketSession: string;
  engineMode: EngineMode;
  blockedReason?: string;
  dataProvider?: string;
  dataHealth: DataHealth;
  providerHealth: ProviderHealth;
  confidenceLevel: ConfidenceLevel;
  expectedDecision?: string;
  actualDecision?: string;
  shadowDecision?: string;
  postOutcome?: string;
  executionImpact: ExecutionImpact;
  entryPriceVirtual?: number;
  stopPriceVirtual?: number;
  targetPriceVirtual?: number;
  virtualOutcome1d?: OutcomeLabel;
  virtualOutcome3d?: OutcomeLabel;
  virtualOutcome5d?: OutcomeLabel;
  virtualOutcome10d?: OutcomeLabel;
  virtualReturnPct1d?: number;
  virtualReturnPct3d?: number;
  virtualReturnPct5d?: number;
  virtualReturnPct10d?: number;
  virtualCheckedAt1d?: string;
  virtualCheckedAt3d?: string;
  virtualCheckedAt5d?: string;
  virtualCheckedAt10d?: string;
  positionSizeVirtual?: number;
  mfe?: number;
  mae?: number;
  currentReturnPct?: number;
  finalReturnPct?: number;
  holdingMinutes?: number;
  outcomeLabel?: OutcomeLabel;
  learningTag?: string;
  regimeTag?: string;
  rawRegime?: string;
  effectiveRegime?: string;
  regimePhase?: RegimePhase;
  regimeAtSignal?: RegimePhase | string;
  regimeAtEntry?: RegimePhase | string;
  regimeAtExit?: RegimePhase | string;
  regimeAtOutcome?: RegimePhase | string;
  r6Trigger?: string;
  sellOnlyActive?: boolean;
  hardBlockActive?: boolean;
  sourceFreshness?: string;
  regimeConfidence?: RegimeConfidence;
  conditionTags?: string[];
  timeWindowTag?: string;
  sectorTag?: string;
  sourceConfidence: SourceConfidence;
  createdAt: string;
  updatedAt: string;
  state?: ShadowLifecycleState;
  liveOrderCreated?: boolean;
  brokerOrderCreated?: boolean;
  brokerOrdersCreated?: 0 | number;
  cohortType?: 'FRESH_SHADOW' | 'BACKLOG_REPAIR' | 'GHOST_REPAIR' | 'RECOVERED_METADATA' | 'QUARANTINED' | 'COUNTERFACTUAL_BLOCKED';
  repairRunId?: string;
  backfillRunId?: string;
  metadataRecovered?: boolean;
  pendingRetryReason?: string;
  quarantinedReason?: string;
  entryPriceSource?: string;
  targetStopSource?: string;
  riskRuleId?: string;
  rMultiple?: number;
  returnR?: number;
  duplicateTelegramSuppressed?: boolean;
  counterfactualRecorded?: boolean;
  labelUpdatedAt?: string;
}
